enableTelemetry: false

nodeLinker: node-modules

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${GITHUB_TOKEN}"

npmScopes:
  sfdc-www:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
