caFilePath: "${NPM_CERT_DIR}/npm-sfdc-certs.pem"

nodeLinker: pnp

npmAlwaysAuth: true

npmAuthIdent: "${NEXUS_USERNAME}:${NEXUS_PASSWORD}"

npmRegistryServer: "https://nexus.soma.salesforce.com/nexus/content/groups/npm-all/"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
